### PR TITLE
fix(rpc): make request header in audit handler

### LINKED ISSUE #4011: [Enhancement]: blobstore rpc auditlog Unmarshal "" string report unexpected
### Contact Details

jianwei1216@qq.com

### Is there an existing issue for this?

- [x] I have searched all the existing issues

### What would you like to be added?

2026/02/28 14:08:00.712915 [INFO] blobstore/sdk/sdk_client.go:465 [prefix.1_x-req-id:427e867d7444170e] done sdk delete request
2026/02/28 14:08:00.712955 [WARN] blobstore/common/rpc/auditlog/request_row.go:223 "", Unmarshal ReqHeader err unexpected end of JSON input
2026/02/28 14:08:00.712982 [WARN] blobstore/common/rpc/auditlog/request_row.go:223 "", Unmarshal ReqHeader err unexpected end of JSON input

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sejust**
close: #4011

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] So on...

### Does this pull request potentially affect one of the following parts:

- [ ] Master
- [ ] MetaNode
- [ ] DataNode
- [ ] ObjectNode
- [ ] AuthNode
- [ ] LcNode
- [ ] Blobstore
- [ ] Client
- [ ] Cli
- [ ] SDK
- [ ] Other Tools
- [x] Common Packages
- [ ] Dependencies
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Review Expection

- [ ] `in-two-days`
- [ ] `weekly`
- [ ] `free-time`
- [x] `whenever`

### CODE REVIEW

File: blobstore/common/rpc/auditlog/auditlog.go [hunk 1]
```diff
@@ -361,29 +363,25 @@ func (j *jsonAuditlog) Audit(ctx context.Context, handler func(context.Context,
 	auditLog.StartTime = startTime.UnixMicro()
 	auditLog.Duration = time.Since(startTime).Microseconds()
 	auditLog.StatusCode = rpc.DetectStatusCode(err)
-
-	fakeRespHeader := make(M)
-	fakeRespHeader["Trace-ID"] = span.TraceID()
+	auditLog.RespHeader["Trace-ID"] = span.TraceID()
```
Comment (yanghonggang) [inline blobstore/common/rpc/auditlog/auditlog.go]: 考虑到跟 Handler 的一致性，看看是否应该使用`textproto.CanonicalMIMEHeaderKey(trace.GetTraceIDKey())`(即 "Blobstore-Tracer-Traceid") 替代 `Trace-ID`

**Comment by yanghonggang** [comment]
lgtm
