### PR TITLE
Fix bug that func `TxUnlinkInode` return result code is wrong when submit raft failed.

### LINKED ISSUE #2366: [Bug]: func `TxUnlinkInode` return result code is wrong when submit raft failed.
**Describe the bug**
 Func `TxUnlinkInode` return result code is wrong when submit raft failed. It return status

**Environment**
develop-3.3.0

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Victor1319**
**What this PR does / why we need it**:
Fix bug that func `TxUnlinkInode` return result code is wrong when submit raft failed.

**Which issue this PR fixes**: fixes #2366

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by leonrayang — DISMISSED** [review]
LGTM

File: metanode/partition_op_inode.go [hunk 1]
```diff
@@ -199,8 +199,8 @@ func (mp *metaPartition) TxUnlinkInode(req *proto.TxUnlinkInodeRequest, p *Packe
 				status = proto.OpErr
 				reply = []byte(err.Error())
 			}
+			p.PacketErrorWithBody(status, reply)
 		}
-		p.PacketErrorWithBody(status, reply)
```
Comment (baijiaruo) [inline metanode/partition_op_inode.go:203]: Is it possible to go here, but not return

**Review by baijiaruo — APPROVED** [review]
LGTM

**Review by leonrayang — APPROVED** [review]
LGTM
