### PR TITLE
fix(rpc): a custom readCloser is used as request.body to count the size of…

### LINKED ISSUE #2120: [Bug]: blobstore access upload no metrics if put with chunked
1. access upload no metrics if put with chunked.

request has no content-length.
```
service_request_length{api="access.put",code="200",method="PUT",service="ACCESS",tag=""} 0
```

2. count put request body, even server did not read.

### PR DESCRIPTION
**Pull request by shuqiang-zheng**
fix(rpc): a custom readCloser is used as request.body to count the size of the request body

in previous version,blobstore access upload no metric if there is no context-length in the request header,now the size is counted when read request body

Fixes #2120

Signed-off-by: shuqiang-zheng <zhengshuqiang@oppo.com>

### CODE REVIEW

**Review by sejust — CHANGES_REQUESTED** [review]

File: blobstore/common/rpc/auditlog/auditlog.go [hunk 1]
```diff
@@ -36,6 +37,22 @@ const (
...
+}
+
+func (reqBody *ReqBodyReadCloser) Read(p []byte) (n int, err error) {
+	n, err = reqBody.reqBody.Read(p)
+	reqBody.size += int64(n)
+	return
+}
+
+func (reqBody *ReqBodyReadCloser) Close() error {
+	return reqBody.Close()
```
Comment (sejust) [inline blobstore/common/rpc/auditlog/auditlog.go:53]: SA5007: infinite recursive call

**Review by sejust — CHANGES_REQUESTED** [review]

File: blobstore/common/rpc/auditlog/auditlog_test.go [hunk 2]
```diff
@@ -74,22 +73,59 @@ func initServer(t *testing.T) {
...
 
 	server = httptest.NewServer(http.HandlerFunc(entryHandler))
+	return server, tmpDir, lc
 }
 
-func close() {
-	server.Close()
-	os.RemoveAll(tmpDir)
-	lc.Close()
+func initNoContextLengthServer(t *testing.T) (server *httptest.Server, tmpDir string, lc LogCloser) {
```
Comment (sejust) [inline blobstore/common/rpc/auditlog/auditlog_test.go:79]: rename all  `ContextLength` to content length.

**Review by sejust — CHANGES_REQUESTED** [review]

**Review by sejust — APPROVED** [review]

**Review by Cloudstriff — APPROVED** [review]
LGTM
