### PR TITLE
[Fix]: Decommissioned disk is still shown in datanode

### LINKED ISSUE #2777: [Bug]: After a disk is offline, you can query disk information through the api
### Contact Details

30685173@qq.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

low (Default)

### Environment

```markdown
- CubeFS version:v3.3.0
- Deployment mode(docker or standalone or cluster):cluster
- Dependent components:
- OS kernel version(Ubuntu or CentOS): euleros   5.10.0-60.18.0.50.h592
- CPU/Memory:  16G
- Others:
```

### Current Behavior

When I offline disk /data0， I checked curl -v "http://master2:17320/disks" and found that the disk was still there

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### CubeFS Log

_No response_

### Anything else? (Additional Context)

_No response_

### PR DESCRIPTION
**Pull request by NaturalSelect**
**What this PR does / why we need it**:

* Add a status `decommission` to `Disk`. 
* When we change `decommission`, we create/remove a `decommissionMark` file in `disk.Path`.
* If a disk is decommissioned, it will not shown in datanode `/disks` API.
* Master synchronous `DecommissionDisks` with datanode using `HearBeatRequest`.
* Cli support decommission disk.
* Cli support to recommission disk.

**Effects:**

_Before decommission:_

```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~]
└─$ curl -v "http://172.16.1.101:8080/disks"
*   Trying 172.16.1.101:8080...
* Connected to 172.16.1.101 (172.16.1.101) port 8080
> GET /disks HTTP/1.1
> Host: 172.16.1.101:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 25 Nov 2023 11:12:44 GMT
< Content-Length: 278
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 172.16.1.101 left intact
{"code":200,"data":{"disks":[{"path":"/home/nature/disk/data1/disk","total":1075732467712,"used":92347719680,"available":928392392704,"unallocated":1075732467712,"allocated":0,"status":2,"restSize":5368709120,"diskRdoSize":5368709120,"partitions":0}],"zone":"default"},"msg":""}
```

_Decommission a disk:_

```log
┌──(root💀LAPTOP-9TS0FG11)-[/home/nature/cubefs]
└─# ./build/bin/cfs-cli disk decommission 172.16.1.101:17310 /home/nature/disk/data1/disk
Mark disk 172.16.1.101:17310:/home/nature/disk/data1/disk to be decommissioned
```

_Request agagin:_

```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~]
└─$ curl -v "http://172.16.1.101:8080/disks"
*   Trying 172.16.1.101:8080...
* Connected to 172.16.1.101 (172.16.1.101) port 8080
> GET /disks HTTP/1.1
> Host: 172.16.1.101:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 25 Nov 2023 11:25:08 GMT
< Content-Length: 58
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 172.16.1.101 left intact
{"code":200,"data":{"disks":[],"zone":"default"},"msg":""}
```

_Debug logs in datanode:_

```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ cat ~/disk/data1/logs/dataNode/dataNode_debug.log | grep checkDecommissionDisks
2023/11/25 19:24:41.612681 [DEBUG] wrap_operator.go:489: action[checkDecommissionDisks] mark /home/nature/disk/data1/disk to be decommissioned
```

*Recommission:*

```log
┌──(root💀LAPTOP-9TS0FG11)-[/home/nature/cubefs]
└─# ./build/bin/cfs-cli disk recommission 172.16.1.101:17310 /home/nature/disk/data1/disk
Mark disk 172.16.1.101:17310:/home/nature/disk/data1/disk to be recommissioned
```

*Debug logs in datanode:*

```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ cat ~/disk/data1/logs/dataNode/dataNode_debug.log | grep checkDecommissionDisks
2023/12/11 11:19:25.434175 [DEBUG] wrap_operator.go:488: action[checkDecommissionDisks] mark /home/nature/disk/data1/disk to be decommissioned
2023/12/11 11:19:37.434252 [DEBUG] wrap_operator.go:483: action[checkDecommissionDisks] mark /home/nature/disk/data1/disk to be undecommissioned
```

**Which issue this PR fixes**:

fixes #2777

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

File: datanode/server_handler.go [hunk 1]
```diff
@@ -35,6 +35,9 @@ var AutoRepairStatus = true
 func (s *DataNode) getDiskAPI(w http.ResponseWriter, r *http.Request) {
 	disks := make([]interface{}, 0)
 	for _, diskItem := range s.space.GetDisks() {
+		if diskItem.decommission {
+			continue
```
Comment (sejust) [inline datanode/server_handler.go:39]: shown decommissioning status in result

**Review by sejust — APPROVED** [review]

File: datanode/server_handler.go (hunk 1 above)
Comment (NaturalSelect) [reply datanode/server_handler.go:39]: OK, I will update it later.

**Review by sejust — DISMISSED** [review]

**Review by sejust — APPROVED** [review]

**Comment by true1064** [comment]
seems that if a disk is mark decommission, here is no judgment that it should no longer be used or trigger data migration to other disk.

How to define dicommission of a disk? Only mark it as dicommission? Or more other actions should be taken such?

**Comment by NaturalSelect** [comment]
> seems that if a disk is mark decommission, here is no judgment that it should no longer be used or trigger data migration to other disk.
> 
> How to define dicommission of a disk? Only mark it as dicommission? Or more other actions should be taken such?

Decommission disk will be scheduled by master.

This pull request just synchronize the status with master.

**Review by true1064 — APPROVED** [review]
LGTM
